# Generated by Django 5.0.2 on 2024-03-01 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Importer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InternalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('document_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('attached_documents', models.FileField(upload_to='internal_documents/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Manager', 'Manager'), ('User', 'User')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BillOfEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(max_length=50, unique=True)),
                ('invoice_reference', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('attached_documents', models.FileField(upload_to='bills_of_entry/')),
                ('importer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping_system.importer')),
            ],
        ),
    ]
